text.low-cased
objectionary/eo-strings pull request #117
Opened 2022-12-30 18:00 UTC by EugeneDar

https://github.com/objectionary/eo-strings/issues/76

2022-12-30 18:16 UTC, EugeneDar commented
@yegor256 @Graur please have a look

2023-01-05 10:18 UTC, Graur requested changes

2023-01-05 10:18 UTC, Graur commented on src/main/eo/org/eolang/txt/text.eo
>    # @todo #57:30min Current implementation using Java.
@EugeneDar looks like you gorget to remove this `todo`

2023-01-05 11:32 UTC, EugeneDar commented
@yegor256 please, have a look

2023-01-08 04:51 UTC, yegor256 commented
@rultor merg

2023-01-08 05:00 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/29506-1374708714)

2023-01-08 05:03 UTC, rultor commented
> @rultor merge

@eugenedar @yegor256 Oops, I failed. You can see the full log [here](https://www.rultor.com/t/29506-1374708714) (spent 3min)

```
    at org.eolang.maven.AssembleMojo.exec (AssembleMojo.java:246)
    at org.eolang.maven.SafeMojo.lambda$execWithTimeout$3 (SafeMojo.java:315)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
    at java.lang.Thread.run (Thread.java:829)
Caused by: org.apache.maven.plugin.MojoExecutionException: 'org.eolang.maven.ParseMojo@2dbda588' execution failed
    at org.eolang.maven.SafeMojo.execute (SafeMojo.java:246)
    at org.eolang.maven.Moja.execute (Moja.java:120)
    at org.eolang.maven.AssembleMojo.exec (AssembleMojo.java:246)
    at org.eolang.maven.SafeMojo.lambda$execWithTimeout$3 (SafeMojo.java:315)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
    at java.lang.Thread.run (Thread.java:829)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: No value present
    at java.util.concurrent.FutureTask.report (FutureTask.java:122)
    at java.util.concurrent.FutureTask.get (FutureTask.java:205)
    at org.eolang.maven.SafeMojo.execWithTimeout (SafeMojo.java:318)
    at org.eolang.maven.SafeMojo.execute (SafeMojo.java:219)
    at org.eolang.maven.Moja.execute (Moja.java:120)
    at org.eolang.maven.AssembleMojo.exec (AssembleMojo.java:246)
    at org.eolang.maven.SafeMojo.lambda$execWithTimeout$3 (SafeMojo.java:315)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
    at java.lang.Thread.run (Thread.java:829)
Caused by: java.lang.IllegalArgumentException: No value present
    at org.eolang.maven.ParseMojo.exec (ParseMojo.java:162)
    at org.eolang.maven.SafeMojo.lambda$execWithTimeout$3 (SafeMojo.java:315)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
    at java.lang.Thread.run (Thread.java:829)
Caused by: java.util.concurrent.ExecutionException: java.util.NoSuchElementException: No value present
    at java.util.concurrent.FutureTask.report (FutureTask.java:122)
    at java.util.concurrent.FutureTask.get (FutureTask.java:191)
    at org.eolang.maven.ParseMojo.exec (ParseMojo.java:159)
    at org.eolang.maven.SafeMojo.lambda$execWithTimeout$3 (SafeMojo.java:315)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
    at java.lang.Thread.run (Thread.java:829)
Caused by: java.util.NoSuchElementException: No value present
    at java.util.Optional.get (Optional.java:148)
    at com.yegor256.tojos.MonoTojo.get (MonoTojo.java:73)
    at org.eolang.maven.ParseMojo.parse (ParseMojo.java:201)
    at org.eolang.maven.ParseMojo.lambda$exec$1 (ParseMojo.java:139)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:515)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
    at java.lang.Thread.run (Thread.java:829)
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
\u001b[0m\u001b[0mcontainer e3ac7fddee1be19e583ec2172d36ab40887fe45fe34f7e1fd0b0c4223a2df45d is dead
Sun 08 Jan 2023 06:03:43 AM CET
```

2023-01-09 18:18 UTC, EugeneDar commented
@yegor256 can you merge it again?

2023-01-09 18:56 UTC, yegor256 commented
@rultor merge

2023-01-09 18:58 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/29506-1376130640)

2023-01-09 19:04 UTC, merged

2023-01-09 19:05 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/29506-1376130640) (took me 7min)