text.chained accept varargs
objectionary/eo-strings pull request #123
Opened 2023-01-19 14:36 UTC by EugeneDar

Closes: https://github.com/objectionary/eo-strings/issues/120

2023-01-19 15:15 UTC, Graur approved these changes
@EugeneDar Looks good, thanks!
@yegor256 Please, have a look

2023-01-19 15:17 UTC, Graur requested changes

2023-01-19 18:39 UTC, EugeneDar commented on src/main/eo/org/eolang/txt/text.eo
>    # Returns concatenaion of two strings
@Graur my fault, I'll fix it.

2023-01-19 18:40 UTC, EugeneDar commented
@Graur please, have a look again

2023-01-20 07:50 UTC, Graur approved these changes
@EugeneDar Looks good, thanks!
@yegor256 Please, take a look

2023-01-20 15:32 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/29793-1398563336)

2023-01-20 15:38 UTC, merged

2023-01-20 15:39 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/29793-1398563336) (took me 7min)