Move sscanf
objectionary/eo-strings pull request #16
Opened 2022-08-17 14:55 UTC by levBagryansky

@Graur , please review
I copied sscanf according to #9

2022-08-18 07:22 UTC, Graur requested changes
@levBagryansky Good one! Just change the license owner

2022-08-18 07:22 UTC, Graur commented on src/main/eo/org/eolang/txt/sscanf.eo
> +#  2022 Eugene Darashkevich
@levBagryansky I think here should be `#  2016-2022 Objectionary.com`

2022-08-18 07:22 UTC, Graur commented on src/main/eo/org/eolang/txt/text.eo
> +#  2022 Eugene Darashkevich
@levBagryansky I think here should be `# 2016-2022 Objectionary.com`

2022-08-18 07:22 UTC, Graur commented on src/main/java/EOorg/EOeolang/EOtxt/EOsscanf.java
> + * Copyright (c) 2022 Eugene Darashkevich
@levBagryansky I think here should be `# 2016-2022 Objectionary.com`

2022-08-18 07:22 UTC, Graur commented on src/test/eo/org/eolang/txt/sscanf-tests.eo
> +# Copyright (c) 2022 Eugene Darashkevich
@levBagryansky I think here should be `# 2016-2022 Objectionary.com`

2022-08-18 07:22 UTC, Graur commented on src/test/java/EOorg/EOeolang/EOtxt/EOsscanfTest.java
> + * Copyright (c) 2022 Eugene Darashkevich
@levBagryansky I think here should be `# 2016-2022 Objectionary.com`

2022-08-18 09:43 UTC, Graur approved these changes
@yegor256 please, have a look

2022-08-19 09:36 UTC, levBagryansky commented
@yegor256 look please

2022-08-19 10:30 UTC, yegor256 commented
@rultor merge

2022-08-19 10:30 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/26544-1220516230)

2022-08-19 10:34 UTC, merged

2022-08-19 10:35 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/26544-1220516230) (took me 4min)

2022-08-19 10:36 UTC, Graur commented
@levBagryansky Thanks!