text.last-index-of implemented
objectionary/eo-strings pull request #61
Opened 2022-09-10 09:26 UTC by EugeneDar

https://github.com/objectionary/eo-strings/issues/43

2022-09-10 09:46 UTC, EugeneDar commented
@Graur as I remember, you also encountered a problem with tests falling only on Windows. Is it possible that there is a similar problem here?

2022-09-12 07:54 UTC, Graur commented
> @Graur as I remember, you also encountered a problem with tests falling only on Windows. Is it possible that there is a similar problem here?

@EugeneDar Yes, this is the same problem, I will fix it as soon as I can

2022-09-14 11:19 UTC, Graur requested changes
@EugeneDar please, check below:

2022-09-14 11:19 UTC, Graur commented on src/test/eo/org/eolang/txt/text-tests.eo
> +
@EugeneDar Please, add tests with corner cases and Unicode characters

2022-09-15 07:30 UTC, EugeneDar commented
@Graur please, have a look again

2022-09-15 08:58 UTC, Graur approved these changes
@EugeneDar Looks good for me
@yegor256 Please, take a look

2022-09-15 09:43 UTC, EugeneDar commented
@yegor256 please, have a look

2022-09-15 09:50 UTC, yegor256 commented
@rultor merge

2022-09-15 09:50 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/26832-1247862551)

2022-09-15 09:53 UTC, merged

2022-09-15 09:53 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/26832-1247862551) (took me 3min)