30 replace
objectionary/eo-strings pull request #86
Opened 2022-10-13 13:47 UTC by levBagryansky

2022-10-13 13:52 UTC, levBagryansky commented
@Graur please review

2022-10-13 14:02 UTC, Graur requested changes
@levBagryansky Good one, just one comment from my side

2022-10-13 14:02 UTC, Graur commented on src/test/eo/org/eolang/txt/regex-tests.eo
> +    $.equal-to "abxxxcd"
@levBagryansky Can you add an extra test with Unicode string? Like `Привет, 世界` or something else

2022-10-13 14:36 UTC, Graur approved these changes
@levBagryansky Looks good to me, thanks!

2022-10-13 14:46 UTC, levBagryansky commented
@yegor256 please check

2022-10-13 17:34 UTC, levBagryansky commented
@yegor256 please take a look

2022-10-14 02:51 UTC, yegor256 commented
@levBagryansky try to give more descriptive titles to your PRs

2022-10-14 02:52 UTC, yegor256 commented
@rultor merge

2022-10-14 02:55 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/27494-1278403017)

2022-10-14 02:58 UTC, merged

2022-10-14 02:59 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/27494-1278403017) (took me 4min)