text.trimmed implemented on eo
objectionary/eo-strings pull request #98
Opened 2022-11-10 13:01 UTC by EugeneDar

https://github.com/objectionary/eo-strings/issues/97

2022-11-10 13:06 UTC, EugeneDar commented
In this implementation `text.trimmed` I implemented only `left-trimmed` and created puzzle finished it.

2022-11-10 13:07 UTC, EugeneDar commented
@Graur @levBagryansky please check.

2022-11-10 13:36 UTC, levBagryansky requested changes
Nice!
Maybe its better to move `up-cased.ascii` into separate attribute?

2022-11-10 13:36 UTC, levBagryansky commented on src/main/eo/org/eolang/txt/text.eo
> +            32
Does it mean 
`up-cased.ascii " "`
?

2022-11-10 13:49 UTC, EugeneDar commented on src/main/eo/org/eolang/txt/text.eo
> +            32
@levBagryansky I'll fix it

2022-11-10 13:56 UTC, EugeneDar commented
@levBagryansky please check again

2022-11-10 14:03 UTC, levBagryansky approved these changes
I like it

2022-11-10 14:22 UTC, EugeneDar commented
@yegor256 please have a look

2022-11-10 14:32 UTC, yegor256 commented
@rultor merge

2022-11-10 14:34 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/28391-1310377723)

2022-11-10 18:47 UTC, EugeneDar commented
@yegor256 please merge it again

2022-11-15 15:42 UTC, EugeneDar commented
@yegor256 please, merge it again

2022-11-15 16:13 UTC, yegor256 commented
@rultor merge

2022-11-15 16:15 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/28391-1315540675)

2022-11-15 16:19 UTC, merged

2022-11-15 16:20 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/28391-1315540675) (took me 5min)